package tests;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import pages.*;

import java.time.Duration;

/**
 * Dashboard feature tests — generated by TestForge from execution-verified runs.
 * Contains 2 tests:
 *   - TC01 - Successful login with valid credentials navigates to dashboard
 *   - TC04 - Dashboard displays all primary sidebar navigation menu items after login
 */
public class DashboardTests {

    private WebDriver driver;
    private WebDriverWait wait;
    private String lastAlertText;
    private LoginPage loginPage;
    private DashboardPage dashboardPage;

    @BeforeMethod
    public void setUp() {
        ChromeOptions options = new ChromeOptions();
        // On CI (GitHub Actions sets CI=true) there is no display, so run headless.
        // Locally it stays headful so you can watch; force headless with -Dheadless=true.
        boolean headless = System.getenv("CI") != null || Boolean.getBoolean("headless");
        if (headless) {
            options.addArguments("--headless=new", "--no-sandbox",
                    "--disable-dev-shm-usage", "--disable-gpu");
        }
        options.addArguments("--window-size=1920,1080", "--disable-notifications", "--remote-allow-origins=*");
        // Selenium Manager (built into Selenium 4) auto-provisions the matching driver.
        driver = new ChromeDriver(options);
        wait = new WebDriverWait(driver, Duration.ofSeconds(15));
        loginPage = new LoginPage(driver);
        dashboardPage = new DashboardPage(driver);
    }

    /** A credential, read from the environment — never committed to source. */
    private static String cred(String var) {
        String v = System.getenv(var);
        if (v == null || v.isBlank()) {
            throw new IllegalStateException(
                    "Environment variable " + var + " is not set. This test signs in, so it "
                  + "needs the account: export " + var + "=... (or add it to your CI secrets).");
        }
        return v;
    }

    private static String envOr(String var, String fallback) {
        String v = System.getenv(var);
        return (v == null || v.isBlank()) ? fallback : v;
    }

    /** A placeholder nothing could resolve. Fails loudly rather than typing it verbatim. */
    private static String unresolved(String token) {
        throw new IllegalStateException("No value for placeholder '" + token
              + "'. Supply it as an environment variable of the same name.");
    }

    @Test(description = "TC01 - Successful login with valid credentials navigates to dashboard")
    public void successfulLoginWithValidCredentialsNavigatesToDashboard() {
        // Step 1: Navigate to the OrangeHRM login page
        driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");

        // Step 2: Type valid username into the Username field
        loginPage.enterUsernameInputField(cred("TESTFORGE_USERNAME"));

        // Step 3: Type valid password into the Password field
        loginPage.enterPasswordInputField(cred("TESTFORGE_PASSWORD"));

        // Step 4: Click the Login button
        loginPage.clickLoginSubmitButton();

        // Step 5: Assert browser URL contains dashboard path
        Assert.assertTrue(driver.getCurrentUrl().contains("/dashboard"),
                "URL should contain '/dashboard' but was: " + driver.getCurrentUrl());

        // Step 6: Assert the Dashboard navigation link is visible
        Assert.assertTrue(dashboardPage.isDashboardNavLinkVisible(), "dashboardNavLink should be visible");

        // Step 7: Assert the Sidepanel navigation is present
        Assert.assertTrue(dashboardPage.isSidepanelNavigationVisible(), "sidepanelNavigation should be visible");

        // Step 8: Assert the Topbar Menu navigation is present
        Assert.assertTrue(dashboardPage.isTopbarMenuNavigationVisible(), "topbarMenuNavigation should be visible");

    }

    @Test(description = "TC04 - Dashboard displays all primary sidebar navigation menu items after login")
    public void dashboardDisplaysAllPrimarySidebarNavigationMenuItemsAfterLogin() {
        // Step 1: Navigate to the OrangeHRM login page
        driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");

        // Step 2: Type valid username
        loginPage.enterUsernameInputField(cred("TESTFORGE_USERNAME"));

        // Step 3: Type valid password
        loginPage.enterPasswordInputField(cred("TESTFORGE_PASSWORD"));

        // Step 4: Click the Login button
        loginPage.clickLoginSubmitButton();

        // Step 5: Assert Admin menu link is visible in sidebar
        Assert.assertTrue(dashboardPage.isAdminSidebarLinkVisible(), "adminSidebarLink should be visible");

        // Step 6: Assert PIM menu link is visible in sidebar
        Assert.assertTrue(dashboardPage.isPIMSidebarLinkVisible(), "pIMSidebarLink should be visible");

        // Step 7: Assert Leave menu link is visible in sidebar
        Assert.assertTrue(dashboardPage.isLeaveSidebarLinkVisible(), "leaveSidebarLink should be visible");

        // Step 8: Assert Recruitment menu link is visible in sidebar
        Assert.assertTrue(dashboardPage.isRecruitmentSidebarLinkVisible(), "recruitmentSidebarLink should be visible");

    }

    @AfterMethod
    public void tearDown() {
        if (driver != null) driver.quit();
    }
}
