package tests;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import pages.*;

import java.time.Duration;

/**
 * Login feature tests — generated by TestForge from execution-verified runs.
 * Contains 4 tests:
 *   - TC02 - Login with invalid credentials shows error and stays on login page
 *   - TC03 - Login with empty credentials does not proceed to dashboard
 *   - TC05 - Password field masks input as password type
 *   - TC06 - OrangeHRM footer link is present on the login page
 */
public class LoginTests {

    private WebDriver driver;
    private WebDriverWait wait;
    private String lastAlertText;
    private LoginPage loginPage;

    @BeforeMethod
    public void setUp() {
        ChromeOptions options = new ChromeOptions();
        // On CI (GitHub Actions sets CI=true) there is no display, so run headless.
        // Locally it stays headful so you can watch; force headless with -Dheadless=true.
        boolean headless = System.getenv("CI") != null || Boolean.getBoolean("headless");
        if (headless) {
            options.addArguments("--headless=new", "--no-sandbox",
                    "--disable-dev-shm-usage", "--disable-gpu");
        }
        options.addArguments("--window-size=1920,1080", "--disable-notifications", "--remote-allow-origins=*");
        // Selenium Manager (built into Selenium 4) auto-provisions the matching driver.
        driver = new ChromeDriver(options);
        wait = new WebDriverWait(driver, Duration.ofSeconds(15));
        loginPage = new LoginPage(driver);
    }

    /** A credential, read from the environment — never committed to source. */
    private static String cred(String var) {
        String v = System.getenv(var);
        if (v == null || v.isBlank()) {
            throw new IllegalStateException(
                    "Environment variable " + var + " is not set. This test signs in, so it "
                  + "needs the account: export " + var + "=... (or add it to your CI secrets).");
        }
        return v;
    }

    private static String envOr(String var, String fallback) {
        String v = System.getenv(var);
        return (v == null || v.isBlank()) ? fallback : v;
    }

    /** A placeholder nothing could resolve. Fails loudly rather than typing it verbatim. */
    private static String unresolved(String token) {
        throw new IllegalStateException("No value for placeholder '" + token
              + "'. Supply it as an environment variable of the same name.");
    }

    @Test(description = "TC02 - Login with invalid credentials shows error and stays on login page")
    public void loginWithInvalidCredentialsShowsErrorAndStaysOnLoginPage() {
        // Step 1: Navigate to the OrangeHRM login page
        driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");

        // Step 2: Type invalid username into the Username field
        loginPage.enterUsernameInputField("invalidUser123");

        // Step 3: Type invalid password into the Password field
        loginPage.enterPasswordInputField("wrongPassword!");

        // Step 4: Click the Login button
        loginPage.clickLoginSubmitButton();

        // Step 5: Assert URL still contains auth/login path
        Assert.assertTrue(driver.getCurrentUrl().contains("/auth/login"),
                "URL should contain '/auth/login' but was: " + driver.getCurrentUrl());

        // Step 6: Assert Login button is still present after failed attempt
        Assert.assertTrue(loginPage.isLoginSubmitButton2Visible(), "loginSubmitButton2 should be visible");

    }

    @Test(description = "TC03 - Login with empty credentials does not proceed to dashboard")
    public void loginWithEmptyCredentialsDoesNotProceedToDashboard() {
        // Step 1: Navigate to the OrangeHRM login page
        driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");

        // Step 2: Click the Login button without entering any credentials
        loginPage.clickLoginSubmitButton();

        // Step 3: Assert URL still contains auth/login path
        Assert.assertTrue(driver.getCurrentUrl().contains("/auth/login"),
                "URL should contain '/auth/login' but was: " + driver.getCurrentUrl());

        // Step 4: Assert Username input field is still visible
        Assert.assertTrue(loginPage.isUsernameInputFieldVisible(), "usernameInputField should be visible");

        // Step 5: Assert Password input field is still visible
        Assert.assertTrue(loginPage.isPasswordInputFieldVisible(), "passwordInputField should be visible");

    }

    @Test(description = "TC05 - Password field masks input as password type")
    public void passwordFieldMasksInputAsPasswordType() {
        // Step 1: Navigate to the OrangeHRM login page
        driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");

        // Step 2: Assert Password field has type attribute set to password
        Assert.assertTrue(loginPage.getPasswordInputFieldText().contains("password"),
                "Expected text 'password' in passwordInputField");

    }

    @Test(description = "TC06 - OrangeHRM footer link is present on the login page")
    public void orangeHRMFooterLinkIsPresentOnTheLoginPage() {
        // Step 1: Navigate to the OrangeHRM login page
        driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");

        // Step 2: Assert OrangeHRM Inc footer link is visible
        Assert.assertTrue(loginPage.isOrangeHRMIncFooterLinkVisible(), "orangeHRMIncFooterLink should be visible");

        // Step 3: Assert OrangeHRM Inc link points to the correct URL
        Assert.assertTrue(loginPage.getOrangeHRMIncFooterLinkText().contains("http://www.orangehrm.com"),
                "Expected text 'http://www.orangehrm.com' in orangeHRMIncFooterLink");

    }

    @AfterMethod
    public void tearDown() {
        if (driver != null) driver.quit();
    }
}
